name = "fast-report-link"
compatibility_date = "2026-08-12"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "fast-report-link-stats"
# Copy this file to wrangler.toml only for Wrangler CLI usage.\ndatabase_id = "REPLACE_WITH_D1_DATABASE_ID"
